create table rank (
    rank_id integer generated by default as identity primary key ,
    rank_name varchar(128) not null,
    rank_salary decimal(14,2) default 0.0,
    unique (rank_name)
);
create table department(
    dep_id integer generated by default as identity primary key,
    dep_name varchar (128) not null,
    dep_phone varchar (18),
    dep_email varchar (64),
    dep_boss_id integer,
    unique (dep_name, dep_phone, dep_email)
);
create table employee(
                         emp_id integer generated by default as identity primary key,
                         emp_lastname varchar (32) not null,
                         emp_firstname varchar (32) not null ,
                         emp_patronymic varchar (32) not null ,
                         emp_dep_id integer,
                         emp_rank_id integer references rank1 (rank_id) on delete set null on update cascade,
                         unique (emp_lastname, emp_firstname, emp_patronymic)
);
alter table department add constraint fk_dep_boss_id foreign key (dep_boss_id)
    references employee (emp_id) on delete set null on update cascade;
alter table employee add constraint fk_emp_dep_id foreign key (emp_dep_id)
    references department (dep_id) on delete set null on update cascade;